version: "3.4"

networks:
    va1-network:
        driver: bridge

services:
    va1-frontend:
        image: va1-frontend:$TAG
        ports:
            - "8080:8080"
        restart: always
        environment:
            base_request_url: http://localhost:5000/
        networks:
            - va1-network
        command: ["nginx", "-g", "daemon off;"]

    va1-backend:
        image: va1-backend:$TAG
        ports:
            - "5000:5000"
        environment:
            db_url1: bolt://va1-neo4j:7687
            db_user1: neo4j 
            db_password1: newPassword
            flask_debug: "True"
            local_run_db_init: "True"
        networks:
            - va1-network

    va1-neo4j:
        image: notchristiangarcia/neo4j:4.4
        environment:
            apoc.initializer.system.1: "CREATE USER neo4j IF NOT EXISTS SET PLAINTEXT PASSWORD 'newPassword' SET PASSWORD CHANGE NOT REQUIRED"
        ports:
            - "7687:7687"
        networks:
            - va1-network
