version: "3.4"

networks:
    va1-network:
        driver: bridge

services:
    va1-frontend:
        image: va1-frontend:$TAG
        ports:
            - "8080:8080"
        restart: always
        environment:
            base_request_url: http://va1-backend:5000
        networks:
            - va1-network
        command: ["nginx", "-g", "daemon off;"]

    va1-backend:
        image: va1-backend:$TAG
        ports:
            - "5000:5000"
        environment:
            db_url1: bolt+ssc://va1-neo4j:7687
            db_user1: neo4j 
            db_passw1: newPassword
        networks:
            - va1-network

    va1-neo4j:
        image: neo4j
        environment:
            NEO4J_AUTH: "neo4j/newPassword"
            NEO4JLABS_PLUGINS: '["apoc", "n10s"]'
        ports:
            - "7687:7687"
        networks:
            - va1-network
