# Your client credentials
client_id: smartfoodshed-va-dev
client_key: va-dev

# The Tapis base URL and tenant id
tapis_base_url: https://icicleai.tapis.io
tenant: icicleai

# The base URL that you app isserved on; this needs to match what was registered with the  OAuth client
#the catalog to a public URL. 
app_base_url: https://vaapibackend.pods.icicle.tapis.io
